### ISSUE TITLE
Add to the AUR

### ISSUE THREAD

**Issue by JustScott** [JustScott/mfa#1]
## To-Do
- [ ] Figure out the exact paths where the project's files will need to be placed
   - [ ] Update the PKGBUILD file to place the project's files in those paths
- [ ] Test the installation process in an Arch VM
- [ ] Create a new Github release using the same version number for itself, the AUR, and PyPI
- [ ] Upload to the AUR
